"""
Even Fibonacci Numbers
 
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
a = 1
b = 2

even_sum = 0

while a <= 4_000_000:
    if a % 2 == 0:
        even_sum += a
    a, b = b, a + b
print(even_sum)
